services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - .secrets.env
    ports:
      - 3000:3000
    volumes:
      - ./apps/homepage:/app/config
      - /mnt/seagate:/mnt/seagate
      - /var/run/docker.sock:/var/run/docker.sock

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    env_file:
      - .shared.env
      - .secrets.env
    volumes:
      - ./ddclient:/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=9090
    env_file:
      - .shared.env
    volumes:
      - ./apps/qbittorrent:/config
      - /mnt/seagate:/seagate
      - /home/dani/Downloads:/watch
    ports:
      - 9090:9090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    env_file:
      - .shared.env
    volumes:
      - ./apps/jackett:/config
      - /home/dani/Downloads:/seagate/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - .shared.env
    volumes:
      - ./apps/sonarr:/config
      - /mnt/seagate:/seagate
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - .shared.env
    volumes:
      - ./apps/radarr:/config
      - /mnt/seagate:/seagate
    ports:
      - 7878:7878
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /mnt/seagate:/seagate
      - ./unpackerr:/config
    environment:
      - UN_LOG_FILE=/seagate/downloads/unpackerr.log
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_WEBSERVER_METRICS=true
    env_file:
      - .shared.env
      - .secrets.env
    ports:
      - 5656:5656

  jellyseerr:
     image: fallenbagel/jellyseerr:latest
     container_name: jellyseerr
     environment:
          - LOG_LEVEL=debug
     ports:
          - 5055:5055
     volumes:
          - ./apps/jellyseerr:/app/config

     restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    env_file:
      - .shared.env
    volumes:
      - ./apps/jellyfin:/config
      - /mnt/seagate/media/sonarr:/data/tvshows
      - /mnt/seagate/media/radarr:/data/movies
      - /mnt/seagate/media/Bellesa:/data/bellesa
      - /mnt/seagate/media/readarr:/data/books
      - /etc/letsencrypt/live/droma82.duckdns.org/:/cert
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  tinfoil:
    image: nginx:alpine
    container_name: tinfoil
    volumes:
      - /mnt/seagate/tinfoil:/usr/share/nginx/html/:ro
      - ./tinfoil:/etc/nginx:ro
    ports:
      - 9000:9000

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_SCHEDULE=0 4 * * *
    env_file:
      - .shared.env
      - .secrets.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    command: --cleanup --http-api-metrics --http-api-token ${SECRET_WATCHTOWER_KEY?error}
    restart: unless-stopped

